{% set name = "ouch" %}
{% set version = "0.6.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ouch-org/ouch/archive/refs/tags/{{ version }}.tar.gz
  sha256: c1430e3b99481eacd1802f6a9cd8dd837d4534cff974a29914d15d8130d19b16

build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cargo-bundle-licenses
    - libclang  # [linux]

test:
  commands:
    - ouch --version
    - ouch --help
    - touch test.txt
    - ouch compress test.txt test.zip

about:
  home: https://github.com/ouch-org/ouch
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Painless compression and decompression in the terminal

extra:
  recipe-maintainers:
    - pavelzw
