{% set name = "ouch" %}
{% set version = "0.5.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ouch-org/ouch/archive/refs/tags/{{ version }}.tar.gz
  sha256: 79562550203d76eecbc7ea47b80d37cccffe08d16dd7a29ac248d38e48c20580

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cargo-bundle-licenses

test:
  commands:
    - ouch --version
    - ouch --help
    - touch test.txt
    - ouch compress test.txt test.zip

about:
  home: https://github.com/ouch-org/ouch
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Painless compression and decompression in the terminal

extra:
  recipe-maintainers:
    - pavelzw
