schema_version: 1

context:
  name: ouch
  version: 0.6.1

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://github.com/ouch-org/ouch/archive/refs/tags/${{ version }}.tar.gz
  sha256: e6265071affab228ba7d3ca85f2206029445038b3a3d96036e9bf02b795ad651

build:
  number: 1

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cargo-bundle-licenses
    - if: linux
      then: libclang

tests:
  - script:
      - ouch --version
      - ouch --help
      - touch test.txt
      - ouch compress test.txt test.7z
      - ouch compress test.txt test.br
      - ouch compress test.txt test.bz2
      - ouch compress test.txt test.bz3
      - ouch compress test.txt test.gz
      - ouch compress test.txt test.lz4
      - ouch compress test.txt test.sz
      - ouch compress test.txt test.xz
      - ouch compress test.txt test.zip
      - ouch compress test.txt test.zst

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Painless compression and decompression in the terminal
  homepage: https://github.com/ouch-org/ouch

extra:
  recipe-maintainers:
    - pavelzw
