schema_version: 1

context:
  name: ouch
  version: "0.7.1"

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://github.com/ouch-org/ouch/archive/refs/tags/${{ version }}.tar.gz
  sha256: 9dadaa3340972347c39e0047668af0e2c59c6128470eeb3fdf86629a3b298443

build:
  number: 0

requirements:
  build:
    - ${{ compiler("rust") }}
    - ${{ compiler("c") }}
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - cmake
    - cargo-bundle-licenses
    - cargo-auditable
    - if: unix
      then:
        - make
    - if: linux
      then: libclang

tests:
  - script:
      - ouch --version
      - ouch --help
      - touch test.txt
      - ouch compress test.txt test.7z
      - ouch compress test.txt test.br
      - ouch compress test.txt test.bz2
      - ouch compress test.txt test.bz3
      - ouch compress test.txt test.gz
      - ouch compress test.txt test.lz4
      - ouch compress test.txt test.sz
      - ouch compress test.txt test.xz
      - ouch compress test.txt test.zip
      - ouch compress test.txt test.zst

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Painless compression and decompression in the terminal
  homepage: https://github.com/ouch-org/ouch

extra:
  recipe-maintainers:
    - pavelzw
